name: 'jaffle_shop'
version: '1.3.1'
config-version: 2

profile: 'bigquery'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      +schema: jaffle_shop
      materialized: table
      staging:
        materialized: view
