version: 2

sources:
  - name: jaffle_shop
    description: The raw data for jaffle_shop
    database: armin-playground
    schema: jaffle_shop
    tables:
      - name: raw_customers
        description: Contains all customers
      
      - name: raw_orders
        description: Contains all orders

      - name: raw_payments
        description: Contains all payments  

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
